{% set name = "tableauserverclient" %}
{% set version = "0.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8d26e50d592eb81059ec698f2946238bcc2d4683d2ee0f2be987bd1299e3bca0

build:
  noarch: python
  number: 0
  script: PYTHONPATH=. {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - pytest-runner
    - versioneer >=0.24
  host:
    - python >=3.7
    - pip
    - pytest-runner
  run:
    - python >=3.7
    - defusedxml >=0.7.1
    - packaging >=22.0
    - requests >=2.28
    - urllib3 ~=1.26.8

test:
  imports:
    - tableauserverclient
    - tableauserverclient.models
    - tableauserverclient.server
    - tableauserverclient.server.endpoint
  requires:
    - black
    - mock
    - mypy
    - pytest >=7.0
    - pytest-subtests
    - requests-mock >=1.0,<2.0

about:
  home: https://github.com/tableau/server-client-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python library for the Tableau Server REST API

  description: |
    Use the Tableau Server Client (TSC) library to increase your productivity
    as you interact with the Tableau Server REST API. With the TSC library you
    can do almost everything that you can do with the REST API, including
    publish workbooks and data sources, create users and groups, and query
    projects, sites, and more.
  doc_url: https://tableau.github.io/server-client-python/docs/
  dev_url: https://github.com/tableau/server-client-python

extra:
  recipe-maintainers:
    - patlougheed
