{% set name = "tableauserverclient" %}
{% set version = "0.33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef28ff132de6211d8667482d364aebb682849ae0392e285994cf6a3e16d1390c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.9
    - pip
    - pytest-runner
    - versioneer >=0.29
  run:
    - python >=3.9
    - defusedxml >=0.7.1
    - packaging >=23.1
    - requests >=2.32
    - typing_extensions >=4.0.1
    - urllib3 >=2.2.2,<3

test:
  imports:
    - tableauserverclient
    - tableauserverclient.models
    - tableauserverclient.server
    - tableauserverclient.server.endpoint
  requires:
    - black ==24.8
    - mypy ==1.4
    - pytest >=7.0
    - pytest-cov
    - pytest-subtests
    - python-build
    - requests-mock >=1.0,<2.0

about:
  home: https://github.com/tableau/server-client-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python library for the Tableau Server REST API

  description: |
    Use the Tableau Server Client (TSC) library to increase your productivity
    as you interact with the Tableau Server REST API. With the TSC library you
    can do almost everything that you can do with the REST API, including
    publish workbooks and data sources, create users and groups, and query
    projects, sites, and more.
  doc_url: https://tableau.github.io/server-client-python/docs/
  dev_url: https://github.com/tableau/server-client-python

extra:
  recipe-maintainers:
    - patlougheed
