{% set name = "tableauserverclient" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57be902e04b6343ce6ec9b9868be619ea1cf32efb0b8053b8ef5af0ed6ecf2b2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - pytest-runner
  host:
    - python >=3.6
    - pip
    - pytest-runner
  run:
    - python >=3.6
    - requests >=2.11,<3.0

test:
  imports:
    - tableauserverclient
    - tableauserverclient.models
    - tableauserverclient.server
    - tableauserverclient.server.endpoint
  requires:
    - pytest
    - mock
    - requests-mock >=1.0,<2.0
    - pycodestyle

about:
  home: https://github.com/tableau/server-client-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python library for the Tableau Server REST API

  description: |
    Use the Tableau Server Client (TSC) library to increase your productivity
    as you interact with the Tableau Server REST API. With the TSC library you
    can do almost everything that you can do with the REST API, including
    publish workbooks and data sources, create users and groups, and query
    projects, sites, and more.
  doc_url: https://tableau.github.io/server-client-python/docs/
  dev_url: https://github.com/tableau/server-client-python

extra:
  recipe-maintainers:
    - patlougheed
